### ISSUE TITLE
the julia part of the code is not working

### ISSUE THREAD

**Issue by ay140** [leogaudin/fract-ol#1]
when i run the code and do ./fractol julia it gaves me a blank window and thats it

**Comment by leogaudin** [comment]
I just tried downloading the repo and running it and it works fine (see attached).

On what machine are you trying to execute it?

<img width="1440" alt="Screenshot 2024-01-20 at 13 50 56" src="https://github.com/leogaudin/fract-ol/assets/91944739/bfead2a1-3f4f-4813-a564-83104403c48a">

**Comment by ay140** [comment]
> I just tried downloading the repo and running it and it works fine (see attached).
> 
> On what machine are you trying to execute it?
> 
> <img alt="Screenshot 2024-01-20 at 13 50 56" width="1440" src="https://private-user-images.githubusercontent.com/91944739/298282895-bfead2a1-3f4f-4813-a564-83104403c48a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NTY0ODMsIm5iZiI6MTcwNTc1NjE4MywicGF0aCI6Ii85MTk0NDczOS8yOTgyODI4OTUtYmZlYWQyYTEtM2Y0Zi00ODEzLWE1NjQtODMxMDQ0MDNjNDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDEzMDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNmY3OWQ3MzAwNTkwYjZlMGNkYTE4MWExYzk4Njg4MzVkMTI2ZDIyYjlkNDdiZGVlMWU4NmUwMTM1ZmVjNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uNEcS1B5kJ5c2kWNh6KyOdwJFzR1vb90oLSrczrY4Lw">

i just cloned it again and it worked fine, i think there was an issue with the first clone.

thank you for the guide and support. appreciate it

**Comment by ay140** [comment]
> > I just tried downloading the repo and running it and it works fine (see attached).
> > On what machine are you trying to execute it?
> > <img alt="Screenshot 2024-01-20 at 13 50 56" width="1440" src="https://private-user-images.githubusercontent.com/91944739/298282895-bfead2a1-3f4f-4813-a564-83104403c48a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NTY0ODMsIm5iZiI6MTcwNTc1NjE4MywicGF0aCI6Ii85MTk0NDczOS8yOTgyODI4OTUtYmZlYWQyYTEtM2Y0Zi00ODEzLWE1NjQtODMxMDQ0MDNjNDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDEzMDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNmY3OWQ3MzAwNTkwYjZlMGNkYTE4MWExYzk4Njg4MzVkMTI2ZDIyYjlkNDdiZGVlMWU4NmUwMTM1ZmVjNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uNEcS1B5kJ5c2kWNh6KyOdwJFzR1vb90oLSrczrY4Lw">
> 
> i just cloned it again and it worked fine, i think there was an issue with the first clone.
> 
> thank you for the guide and support. appreciate it

there is one thing in the subject, mandatory part which is: 
You must be able to create different Julia sets by passing different parameters to
the program
may i know if your code handle this and how to test it? cause i tried but i couldnt

**Comment by leogaudin** [comment]
> > > I just tried downloading the repo and running it and it works fine (see attached).
> > > On what machine are you trying to execute it?
> > > <img alt="Screenshot 2024-01-20 at 13 50 56" width="1440" src="https://private-user-images.githubusercontent.com/91944739/298282895-bfead2a1-3f4f-4813-a564-83104403c48a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NTY0ODMsIm5iZiI6MTcwNTc1NjE4MywicGF0aCI6Ii85MTk0NDczOS8yOTgyODI4OTUtYmZlYWQyYTEtM2Y0Zi00ODEzLWE1NjQtODMxMDQ0MDNjNDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDEzMDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNmY3OWQ3MzAwNTkwYjZlMGNkYTE4MWExYzk4Njg4MzVkMTI2ZDIyYjlkNDdiZGVlMWU4NmUwMTM1ZmVjNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uNEcS1B5kJ5c2kWNh6KyOdwJFzR1vb90oLSrczrY4Lw">
> > 
> > 
> > i just cloned it again and it worked fine, i think there was an issue with the first clone.
> > thank you for the guide and support. appreciate it
> 
> there is one thing in the subject, mandatory part which is: You must be able to create different Julia sets by passing different parameters to the program may i know if your code handle this and how to test it? cause i tried but i couldnt

If I remember correctly, I personally took the liberty to assign the "J" key to generate random constant values to show different variations of Julia.

If you want to play it safe, you can allow the user to enter those constants as command-line parameters and create some "float atoi"/atof to parse it.

But if it takes you too much time I'd say my workaround can pass and be justified.
